<div>
    @livewire('navigation')
    @livewire('hero')
    @livewire('trust')
    @livewire('services')
    @livewire('process')
    @livewire('vision')
    @livewire('image-showcase')
    @livewire('contact')
    @livewire('footer')
</div>
